### ISSUE TITLE
Renaming replays in the backups folder doesn't work

### ISSUE THREAD

**Issue by zero318** [raviddog/threplay#1]
I copied a replay from TH8 into the backups folder and then tried to rename it by typing in the right rename box, but pressing enter set the name to "(no single replay selected).rpy" instead of what I had typed.

![Before1](https://user-images.githubusercontent.com/20288925/57573056-b7880200-73f0-11e9-9534-9c425d71266f.png)
![After1](https://user-images.githubusercontent.com/20288925/57573058-b8209880-73f0-11e9-995b-a1dac303fbfe.png)

Upon further testing, if a replay is selected from the regular replays folder when pressing enter to rename the replay in the backups folder, the backup replay will be renamed to match the other selected replay instead of what was typed.

![Before2](https://user-images.githubusercontent.com/20288925/57573057-b7880200-73f0-11e9-954f-1ff6c16783cb.png)
![After2](https://user-images.githubusercontent.com/20288925/57573059-b8209880-73f0-11e9-8c75-5e8599a0782c.png)

**Comment by raviddog** [comment]
Fixed. It was an oversight when I copy pasted the renaming code for the backup folder and forgot to change some part.
